#!/usr/bin/env python3
"""
AUTOGENERATED CLEANUP SCRIPT
Review this script carefully before running.
This script will remove scientifically invalid sweep directories.
Date: 2026-05-06T21:39:29.642272
"""

import shutil
from pathlib import Path

# Scientific cleanup: Remove directories with inadequate time horizons
# Removing: profile_sweep_quick_20260428-214333 (invalid time horizon or malformed data)
invalid_dir = Path("profile_sweep_quick_20260428-214333")
if invalid_dir.exists():
    print(f"Removing {sweep["name"]}...")
    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY
    # shutil.rmtree(invalid_dir)
else:
    print(f"Directory {sweep["name"]} already removed")

# Removing: profile_sweep_quick_20260428-224203 (invalid time horizon or malformed data)
invalid_dir = Path("profile_sweep_quick_20260428-224203")
if invalid_dir.exists():
    print(f"Removing {sweep["name"]}...")
    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY
    # shutil.rmtree(invalid_dir)
else:
    print(f"Directory {sweep["name"]} already removed")

# Removing: profile_sweep_quick_20260428-224245 (invalid time horizon or malformed data)
invalid_dir = Path("profile_sweep_quick_20260428-224245")
if invalid_dir.exists():
    print(f"Removing {sweep["name"]}...")
    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY
    # shutil.rmtree(invalid_dir)
else:
    print(f"Directory {sweep["name"]} already removed")

# Removing: profile_sweep_quick_20260428-225241 (invalid time horizon or malformed data)
invalid_dir = Path("profile_sweep_quick_20260428-225241")
if invalid_dir.exists():
    print(f"Removing {sweep["name"]}...")
    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY
    # shutil.rmtree(invalid_dir)
else:
    print(f"Directory {sweep["name"]} already removed")

# Removing: profile_sweep_quick_20260428-225500 (invalid time horizon or malformed data)
invalid_dir = Path("profile_sweep_quick_20260428-225500")
if invalid_dir.exists():
    print(f"Removing {sweep["name"]}...")
    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY
    # shutil.rmtree(invalid_dir)
else:
    print(f"Directory {sweep["name"]} already removed")

# Removing: profile_sweep_quick_20260429-074317 (invalid time horizon or malformed data)
invalid_dir = Path("profile_sweep_quick_20260429-074317")
if invalid_dir.exists():
    print(f"Removing {sweep["name"]}...")
    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY
    # shutil.rmtree(invalid_dir)
else:
    print(f"Directory {sweep["name"]} already removed")

# Removing: profile_sweep_quick_20260430-062033 (invalid time horizon or malformed data)
invalid_dir = Path("profile_sweep_quick_20260430-062033")
if invalid_dir.exists():
    print(f"Removing {sweep["name"]}...")
    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY
    # shutil.rmtree(invalid_dir)
else:
    print(f"Directory {sweep["name"]} already removed")

# Removing: profile_sweep_quick_20260501-074244 (invalid time horizon or malformed data)
invalid_dir = Path("profile_sweep_quick_20260501-074244")
if invalid_dir.exists():
    print(f"Removing {sweep["name"]}...")
    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY
    # shutil.rmtree(invalid_dir)
else:
    print(f"Directory {sweep["name"]} already removed")

print("Cleanup script completed. Review results above.")
