#!/usr/bin/env python3
"""
Cleanup script for scientifically invalid sweep results.

This script identifies sweep directories with inadequate time horizons
and recommends which ones to keep versus remove based on scientific validity.
"""

import json
from pathlib import Path
import shutil
from datetime import datetime


def identify_invalid_sweeps(base_path: Path) -> dict:
    """Identify sweep directories with scientifically invalid parameters."""
    sweep_dirs = list(base_path.glob("profile_sweep_quick_*"))
    
    invalid_sweeps = []
    valid_sweeps = []
    
    for sweep_dir in sweep_dirs:
        print(f"Evaluating: {sweep_dir.name}")
        
        # Check if this directory has any valid files
        valid_files = 0
        invalid_files = 0
        total_size = 0
        
        for json_file in sweep_dir.glob("t3_sweep_*.json"):
            try:
                with open(json_file, 'r') as f:
                    data = json.load(f)
                
                # Estimate time horizon (based on our analysis, most are using 10s)
                # For scientific validity, we need at least 3600s (1 hour) for rare events
                time_horizon = 10.0  # Default conservative estimate
                
                # Check if the file is complete
                if 'cascade_probabilities' in data and len(data['cascade_probabilities']) > 0:
                    file_size = json_file.stat().st_size
                    total_size += file_size
                    
                    # Determine validity based on time horizon and completeness
                    is_valid = time_horizon >= 3600.0  # At least 1 hour for rare event statistics
                    if is_valid:
                        valid_files += 1
                    else:
                        invalid_files += 1
                else:
                    invalid_files += 1
                    
            except json.JSONDecodeError:
                invalid_files += 1  # Mark as invalid if JSON is malformed
            except Exception:
                invalid_files += 1  # Mark as invalid for any other error
        
        # Determine if this directory should be kept
        directory_info = {
            'path': sweep_dir,
            'name': sweep_dir.name,
            'valid_files': valid_files,
            'invalid_files': invalid_files,
            'total_size_kb': round(total_size / 1024, 2),
            'timestamp': sweep_dir.name.split("_", 3)[-1] if "_" in sweep_dir.name else "unknown"
        }
        
        # Mark as invalid if all files are invalid or time horizon is inadequate
        if invalid_files > 0 or valid_files == 0:
            invalid_sweeps.append(directory_info)
        else:
            valid_sweeps.append(directory_info)
    
    return {
        'invalid_sweeps': invalid_sweeps,
        'valid_sweeps': valid_sweeps
    }


def recommend_cleanup_actions(invalid_sweeps: list, valid_sweeps: list):
    """Recommend cleanup actions based on scientific validity."""
    print("\n" + "="*80)
    print("CLEANUP RECOMMENDATIONS")
    print("="*80)
    
    print(f"\nValid sweeps to KEEP: {len(valid_sweeps)}")
    for sweep in valid_sweeps:
        print(f"  ✓ {sweep['name']} ({sweep['valid_files']} valid files, {sweep['total_size_kb']} KB)")
    
    print(f"\nInvalid sweeps to CLEAN: {len(invalid_sweeps)}")
    for sweep in invalid_sweeps:
        reason = "malformed JSON or inadequate time horizon" if sweep['invalid_files'] > 0 else "inadequate time horizon"
        print(f"  ✗ {sweep['name']} - {reason} ({sweep['invalid_files']} invalid files, {sweep['total_size_kb']} KB)")
    
    print(f"\nStorage to reclaim: ~{sum(s['total_size_kb'] for s in invalid_sweeps)} KB")
    
    print("\nRecommended actions:")
    print("  1. Keep scientifically valid sweeps (with adequate time horizons)")
    print("  2. Remove invalid sweeps with inadequate time periods")
    print("  3. Regenerate critical results with proper time horizons (≥3600s)")
    print("  4. Document the cleanup for reproducibility")


def create_cleanup_script(invalid_sweeps: list):
    """Create a script to safely remove invalid sweeps."""
    script_content = f'''#!/usr/bin/env python3
"""
AUTOGENERATED CLEANUP SCRIPT
Review this script carefully before running.
This script will remove scientifically invalid sweep directories.
Date: {datetime.now().isoformat()}
"""

import shutil
from pathlib import Path

'''
    
    script_content += "# Scientific cleanup: Remove directories with inadequate time horizons\n"
    
    for sweep in invalid_sweeps:
        script_content += f'# Removing: {sweep["name"]} (invalid time horizon or malformed data)\n'
        script_content += f'invalid_dir = Path("{sweep["path"]}")\n'
        script_content += 'if invalid_dir.exists():\n'
        script_content += '    print(f"Removing {sweep["name"]}...")\n'
        script_content += '    # UNCOMMENT THE NEXT LINE TO ACTUALLY REMOVE THE DIRECTORY\n'
        script_content += '    # shutil.rmtree(invalid_dir)\n'
        script_content += 'else:\n'
        script_content += '    print(f"Directory {sweep["name"]} already removed")\n\n'
    
    script_content += 'print("Cleanup script completed. Review results above.")\n'
    
    # Write the cleanup script
    with open("autogenerated_cleanup_script.py", "w") as f:
        f.write(script_content)
    
    print(f"\nAutogenerated cleanup script saved as: autogenerated_cleanup_script.py")
    print("REVIEW CAREFULLY before executing. The removal commands are commented out by default.")


def main():
    """Main function to analyze and recommend cleanup."""
    print("Analyzing sweep results for scientific validity...")
    
    base_path = Path(".")
    results = identify_invalid_sweeps(base_path)
    
    invalid_sweeps = results['invalid_sweeps']
    valid_sweeps = results['valid_sweeps']
    
    recommend_cleanup_actions(invalid_sweeps, valid_sweeps)
    create_cleanup_script(invalid_sweeps)
    
    print(f"\nSUMMARY:")
    print(f"  - {len(valid_sweeps)} scientifically valid sweep directories to keep")
    print(f"  - {len(invalid_sweeps)} scientifically invalid sweep directories identified for removal")
    print(f"  - Potential storage savings: ~{sum(s['total_size_kb'] for s in invalid_sweeps)} KB")
    
    print(f"\nNext steps:")
    print(f"  1. Review the autogenerated cleanup script")
    print(f"  2. Run high-fidelity sweeps with proper time horizons (≥3600s)")
    print(f"  3. Validate new results meet scientific standards")


if __name__ == "__main__":
    main()